controller:
  admin:
    user: admin
    password: admin123
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    hostName: jenkins.local
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
    tls: []
  installPlugins:
    - kubernetes:4384.v1b_6367f393d9
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.8.0
    - configuration-as-code:2006.v001a_2ca_6b_574
    - docker-plugin
    - docker-workflow:latest

agent:
  additionalContainers:
    - sideContainerName: dind
      image:
        repository: docker
        tag: dind
#        TO DO: env is not in the official chart values, check the indentation or another key if needed, otherwise in the UI
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command: "dockerd-entrypoint.sh"
      args: "--host=tcp://0.0.0.0:2375"
      privileged: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
  podLabels:
    jenkins-jenkins-agent: "true"
    customJenkinsLabels: "jenkins-jenkins-agent"
  envVars:
    - name: DOCKER_HOST
      value: tcp://localhost:2375