resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: currency-converter-ingress
    path: ingress-patch.json

