---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAuJX5LQzS1PQVy1Pi218w62AeKRSBWBMU9FA+3bOvS6BRATS6hh74YitVEtuIav8YdkFqz7jy8Uzi2e+6Mxr0KnrqscN1RhCKjW/8rrZpmqFSF4C+DFa5aWsilYCjnVqCB4qrIC/Ydh+9nMsoNFZ6jVS5cr+msFdOqBLJ5QW68P721qrko94nuGAsJ/YWRjFQ3uQXxs81rxW4AvGPxG+t9DCrzx36IKAUt7LXnNRFVReYEvyTGM7paKe1uVRwnPGJCW4W70eVB5YcBBi7f/rP7o/WtVBNSn0vJTgGyhpxlJI+M4W2BIOffR+1AldR7loDLf3LyZTlhRd/jRSQPOcWpk0ju6ACvMYbD1z75vzDBXBNWWWcj5BXfTkItOnWy5A3W7JkdwbiiZc7tZoXMyMABUBaxpJfqcNWwVG6JykoiLKivtjME+1JXomPsN3SjdtthpdOMOvyRmJMye2bawXVePXLCBM4jfaIFIWrWvTPlftkCMrb49cBpp7sf5X2G/IcinuH6CnT44XWevqB3kONm8EpPLvGCq4CuOCJOcO8vCXN1uM0jKGOTNm/HpzO8LCVHamijbdvw1hNu5Ory4SS+fOdqEdOc6kWmeI1xMiwBuUXs/inzj8hwEG2DwKRJmh9FfyfCEog8Rhu6eZYiwfYiB2qFrOIm9m9Q0/NfXTychuQ8W7mP9XDPrYn/4o0CTjOMGEe4tWxURPv7QXo9cTVY35J3t9f2rH3jp4Nh+Tnrq+29ZSJ0gKZ958L5t9sgeqAodw==
  template:
    metadata:
      name: api-keys
      namespace: default
    type: Opaque
