---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgDSQElmBA567MjRQC6n7wZdUJ4K2LyKXu1WM5RuDzt1UGFKY5NLZcfmza41dvVYLVXsL9z4U3ORGgEbM2c2ZtTI5zGxxIlYpuNSvQQszi10QrGQeBcUpEhiD7PiwEPeDjnysGnJgUtbM+1MamhIqkwCpJ6NwcU0FFAYClDmaavCf1vURGNZQjYl3cPFZtoHnzX/MOTtz8LLqNj6lk31xSBVWo1OGXLf8tLfdBnh6kYFlBjnM5uxLtTtlkQ6EO5CQqy1u1UZnEmE4/fJEYTD8vnTtJH/DcYNWKFjQ4BCz8kfZ+iCfdOjfn5difrSECiLu3fU9rdQqdne0/bhQxeSSqVjBGLv4VAk7HGbRQfQsT99iYXR5zuO3nAwsIUs8vGsVVvCKU38MU7bY2TgaLuAiUaIYY0MzEQp0fkicr19r738+5Y9anz4Z/olABKzVbdBi5f0Ak0DqydYaPFVa3XIBH9K7eLoFjt0P/ckUQO4wr+IWt2kV8tFfX6rRwFR7BsyPM+Cz2hVZJU4e96wfZNxvFH0UrtMWMFnmcZrknVcEWa+5YFgtS12KWnkz4IGMR7jjw11AD7jogfGqGBKe6+d/M9O+u3y2snoKH9VrzJJr6dLw+QcrL2eMc1TGqRH4BEy/d4CINGDWVhkuGkQ57HWRffgqUZ3KEiaRZWNulqeVcH8TtU+RFi9KQ3oU44giZ7M7ac9TjRx8u0AANlCHjxcjnFFLE9IANbjrPsnuY+WWrBvwgjfh5lDcUuoXskuzl0qujFb5g==
  template:
    metadata:
      name: api-keys
      namespace: default
    type: Opaque
